---
- name: Playbook to customize existing qcow2 image(s)
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Check if image exists already
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: check-images-exist

    - name: Run customization tasks
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: customize-images
