---
- name: Playbook to customize existing qcow2 image(s)
  hosts: localhost
  gather_facts: False
  become: False

  tasks:
    - name: Run customization tasks
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: customize-images
