---
- name: This playbook does a full lifecycle of qcow2 image(s) using the image-builder service
  hosts: localhost
  gather_facts: False
  become: False

  tasks:
    - name: Get refresh token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Get available composes
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-composes

    - name: Verify composes finished
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: verify-compose-finished

    - name: Upload images to rhosp
      tags:
        - upload
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: upload-to-rhosp

    - name: Delete older image versions
      tags:
        - delete
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: delete-images
