---
- name: Playbook to upload new images versions to OpenStack
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Check if image exists already
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: check-images-exist

    - name: Get refresh token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Get available composes
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-composes

    - name: Verify composes finished
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: verify-compose-finished

    - name: Upload images to rhosp
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: upload-to-rhosp
