---
- name: Playbook to delete older image versions from OpenStack
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Delete older image versions
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: delete-images
