---
- name: Playbook to check event information sent by Github
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    pr_merged_main: false

  tasks:
    - name: Set fact if this is a PR merged on main branch
      when:
        - awx_webhook_event_type is defined
        - awx_webhook_event_type == "pull_request"
        - awx_webhook_payload['pull_request']['merged'] | bool
        - awx_webhook_payload['pull_request']['base']['ref'] == "main"
      ansible.builtin.set_fact:
        pr_merged_main: true

    - name: Fail if this is any other event
      when: not pr_merged_main
      ansible.builtin.fail:
        msg: The event is not a pull request merged on the main branch

    - name: Information about this release
      ansible.builtin.debug:
        msg:
          - "Title:  {{ awx_webhook_payload.pull_request.title }} (PR#{{ awx_webhook_payload.pull_request.number }})"
          - "Merged: {{ awx_webhook_payload.pull_request.merged_at }}"
          - "Link:   {{ awx_webhook_payload.pull_request.html_url }}"
          - "Body:   {{ awx_webhook_payload.pull_request.body }}"
