---
- name: Playbook to delete old composes from Red Hat's image builder service
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
    - name: Get refresh token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Get previous composes
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-composes

    - name: Deleting these composes
      debug:
        msg: "{{ item.image_name }}"
      loop: "{{ composes.json.data }}"
      loop_control:
        label: "{{ item.id }}"
      vars:
        image_name: "{{ item.image_name | default(omit) }}"
      when:
        - image_name is defined
        - images | selectattr('name', 'match', image_name) | list | length > 0

    - name: Delete compose
      ansible.builtin.uri:
        url: "{{ api_endpoint }}/composes/{{ item.id }}"
        method: DELETE
        headers:
          Authorization: Bearer {{ refresh_token.json.access_token }}
          Content-Type: application/json
        status_code: 200
      loop: "{{ composes.json.data }}"
      loop_control:
        label: "{{ item.id }}"
      vars:
        image_name: "{{ item.image_name | default(omit) }}"
      when:
        - image_name is defined
        - images | selectattr('name', 'match', image_name) | list | length > 0
