---
- name: Playbook to download images
  hosts: localhost
  connection: local
  become: False
  gather_facts: False

  tasks:
    - name: Get refresh token
      tags: 
        - token
        - always
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Check if image exists
      ansible.builtin.stat:
        path: "{{ storage_dir | default('.') }}/{{ item.name }}-{{ item.release_id }}.qcow2"
      loop: "{{ images }}"
      loop_control:
        label: "{{ item.name }}"
      register: filecheck

    - name:  Show file status
      debug:
        msg: "{{ item.stat }}"
      loop: "{{ filecheck.results }}"
      loop_control:
        label: "{{ item.invocation.module_args.path }}"
      when: not item.stat.exists

    - name: Request creation of images
      tags:
        - compose
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: request-image-creation

    - name: Download images
      tags:
        - download
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: download-images

