---
- name: This playbook creates qcow2 image(s) using the image-builder service
  hosts: localhost
  gather_facts: False
  become: False

  tasks:
    - name: Check if image exists already
      tags:
        - check
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: check-images

    - name: Request creation of images
      tags:
        - compose
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: request-image-creation

    - name: Download images
      tags:
        - download
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: download-images

    - name: Run customization tasks on images
      tags:
        - customize
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: customize-images

    - name: Upload images to rhosp
      tags:
        - upload
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: upload-to-rhosp

    - name: Delete older image versions
      tags:
        - delete
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: delete-images
