---
- name: Playbook to do full lifecycle of qcow2 image(s) using Red Hat's Insights Image Builder
  hosts: localhost
  gather_facts: false
  become: false

  pre_tasks:
    - when: release_id is not defined
      block:
      - name: Gather date_time facts
        ansible.builtin.setup:
          gather_subset: date_time

      - ansible.builtin.set_fact:
          release_id: "{{ ansible_facts.date_time.iso8601_basic_short }}"

  tasks:
    - name: Check if image exists already
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: check-images-exist

    - name: Get refresh token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Request creation of images
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: request-image-creation

    - name: Verify composes finished
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: verify-compose-finished

    - name: Renew token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Download images
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: download-images

    - name: Run customization tasks
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: customize-images

    - name: Upload images to rhosp
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: upload-to-rhosp

    - name: Delete older image versions
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: delete-images
