---
- name: Playbook to do full lifecycle of qcow2 image(s) using Red Hat's image builder service
  hosts: localhost
  gather_facts: False
  become: False

  tasks:
    - name: Check if image exists already
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: check-images-exist

    - name: Get refresh token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Request creation of images
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: request-image-creation

    - name: Wait at least five minutes before checking
      ansible.builtin.pause:
        minutes: 5

    - name: Verify composes finished
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: verify-compose-finished

    - name: Renew token
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: get-refresh-token

    - name: Download images
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: download-images

    - name: Run customization tasks
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: customize-images

    - name: Upload images to rhosp
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: upload-to-rhosp

    - name: Delete older image versions
      ansible.builtin.import_role:
        name: image_builder
        tasks_from: delete-images
