---
- name: Set fact with release_str if release_id is set
  ansible.builtin.set_fact:
    release_str: -{{ release_id }}
  when: release_id is defined

- name: Check if image exists
  ansible.builtin.stat:
    path: "{{ path }}"
  loop: "{{ images }}"
  loop_control:
    label: "{{ path }}"
  vars:
    path: "{{ storage_dir | default('.') }}/{{ item.name }}{{ release_str | default('') }}.qcow2"
  register: filecheck

- name: Show file status
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  when: not item.stat.exists
  ansible.builtin.debug:
    msg: "{{ item.stat }}"
