---
- name: Check if image exists
  ansible.builtin.stat:
    path: "{{ storage_dir | default('.') }}/{{ item.name }}-{{ release_id }}.qcow2"
  loop: "{{ images }}"
  loop_control:
    label: "{{ item.name }}"
  register: filecheck

- name:  Show file status
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  when: not item.stat.exists
  debug:
    msg: "{{ item.stat }}"
