---
- name: Set fact with release_str if release_id is set
  ansible.builtin.set_fact:
    release_str: "-{{ release_id }}"
  when: release_id is defined

- name: Check if image exists
  ansible.builtin.stat:
    path: "{{ path }}"
  loop: "{{ images }}"
  loop_control:
    label: "{{ path }}"
  vars:
    requests: "{{ item.requests | default({}) }}"
    file_name: "{{ item.name }}{{ release_str | default('') }}"
    image_requests: "{{ default_image_request | ansible.builtin.combine(requests, recursive=true) }}"
    file_extension: "{{ image_type_to_extension[image_requests.image_type] | default(item.requests.image_type) }}"
    path: "{{ storage_dir }}/{{ file_name }}.{{ file_extension }}"
  register: filecheck

- name: Show file status
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  ansible.builtin.debug:
    msg: "{{ item.stat }}"
