---
- name: Set fact with release_str if release_id is set
  ansible.builtin.set_fact:
    release_str: "-{{ release_id }}"
  when: release_id is defined

- name: Check if image exists
  ansible.builtin.stat:
    path: "{{ path }}"
  loop: "{{ images }}"
  loop_control:
    label: "{{ path }}"
  vars:
    file_name: "{{ item.name }}{{ release_str | default('') }}"
    file_extension: "{{ image_type_to_extension[item.compose.image_type] | default(item.compose.image_type) }}"
    path: "{{ storage_dir }}/{{ file_name }}.{{ file_extension }}"
  register: filecheck

- name: Show file status
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  #when: not item.stat.exists
  ansible.builtin.debug:
    msg: "{{ item.stat }}"
