- name: Run virt-customize
  ansible.builtin.shell: >
    virt-customize -a {{ item.invocation.module_args.path }}
    --timezone Europe/Berlin
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  async: 1200
  poll: 0
  register: customize
  environment:
    LIBGUESTFS_BACKEND: direct
  when: item.stat.exists

- name: Confirm image customization finished
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
  delay: 60
  loop: "{{ customize.results }}"
  loop_control:
    label: "{{ item.item.invocation.module_args.path }}"
