---
- name: Run virt-customize command
  ansible.builtin.shell:
    virt-customize -a {{ image_path }} {{ customizations }}
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ image_path }}"
  environment:
    LIBGUESTFS_BACKEND: direct
  when:
    - item.item.offline_customization.virt_customize is defined | default(false)
  vars:
    image_path: "{{ item.invocation.module_args.path }}"
    customizations: "{{ item.item.offline_customization.virt_customize | join(' ') }}"

# virt-edit can only edit one single file per run, so have to do a nested loop
- name: Run virt-edit commands
  ansible.builtin.include_tasks: virt-edit.yaml
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ image_path }}"
  when:
    - item.item.offline_customization.virt_edit is defined | default(false)
  vars:
    image_path: "{{ item.invocation.module_args.path }}"
    customizations: "{{ item.item.offline_customization.virt_edit }}"
