---
- name: Get refresh_token from offline_token
  ansible.builtin.uri:
    url: "{{ sso_endpoint }}"
    method: POST
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ offline_token }}"
    body_format: form-urlencoded
    status_code: 200
  register: refresh_token
