- name: Upload images to rhosp
  openstack.cloud.image:
    name: "{{ item.name }}"
    id: "{{ (compose_status_request.results | selectattr('json.request.image_name', 'match', item.name) | map(attribute='item.json.id') | first) | default(omit) }}"
    container_format: "{{ item.disk_format | default('bare') }}"
    disk_format: "{{ item.disk_format | default('qcow2') }}"
    state: "{{ item.state | default('present') }}"
    filename: "{{ storage_dir | default('.') }}/{{ item.name }}-{{ item.release_id }}.qcow2"
    tags: "{{ (item.tags | default([])) + [item.release_id] | default(omit) }}"
    properties: "{{ item.properties | default(omit) }}"
  loop: "{{ images }}"
  loop_control:
    label: "{{ item.name }}"
