---
- name: Upload images to rhosp
  openstack.cloud.image:
    name: "{{ image.name }}"
    id: "{{ (compose_status_request.results |
      selectattr('json.request.image_name', 'match', image.name) |
      map(attribute='item.json.id') | first) | default(omit) }}"
    container_format: "{{ image.container_format | default('bare') }}"
    disk_format: "{{ image.disk_format | default('qcow2') }}"
    state: "{{ image.state | default('present') }}"
    filename: "{{ item.invocation.module_args.path }}"
    tags: "{{ (image.tags | default([])) + [release_id] | default(omit) }}"
    properties: "{{ image.properties | default(omit) }}"
  loop: "{{ filecheck.results }}"
  loop_control:
    label: "{{ image.name }}"
  when: item.stat.exists
  vars:
    image: "{{ item.item }}"
