---
# Default to empty for clean exit of playbooks. This sould be overridden
# by the user in group_vars.
images: []
# Default image request is an x86_64 image with qcow2 format and uploaded to
# aws s3, so that it can be downloaded. Image definitions can override all or
# part of this structure. See examples.
default_image_request:
  architecture: x86_64
  image_type: guest-image
  upload_request:
    options: {}
    type: aws.s3

# Where to copy the images when downloading and customizing
storage_dir: .

# How many times to check the status of image builds
compose_check_retries: 15

# For how long to wait between each image build status check
compose_check_wait_secs: 60

# How many loops of `compose_check_retries` to do, while renewing token in between loops (if expired)
compose_check_max_loops: 5
