---
# Default to empty for clean exit of playbooks. This sould be overridden
# by the user in group_vars.
images: []

# Endpoint required to request offline token
sso_endpoint: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

# Endpoint required to interact with image builer
api_endpoint: https://console.redhat.com/api/image-builder/v1

# Where to copy the images when downloading and customizing
storage_dir: .

# How many times to check the status of image builds
compose_check_retries: 15

# For how long to wait between each image build status check
compose_check_wait_secs: 60

# How many loops of `compose_check_retries` to do, while renewing token in between loops (if expired)
compose_check_max_loops: 5

# Map image types to file extensions
image_type_to_extension:
  guest-image: qcow2
  edge-commit: tar
  rhel-edge-commit: tar
  edge-installer: iso
  rhel-edge-installer: iso
  image-installer: iso
  vsphere: vmdk
  vsphere-ova: ova
